$background = 050202
$onBackground = f8e0df
$surface = 050202
$surfaceDim = 050202
$surfaceBright = 130b0b
$surfaceContainerLowest = 000000
$surfaceContainerLow = 080303
$surfaceContainer = 0b0505
$surfaceContainerHigh = 0e0707
$surfaceContainerHighest = 110909
$onSurface = f8e0df
$surfaceVariant = 110909
$onSurfaceVariant = bca6a5
$outline = 847170
$outlineVariant = 544443
$inverseSurface = fff8f7
$inverseOnSurface = 5d5352
$shadow = 000000
$scrim = 000000
$surfaceTint = 372222
$primary = f8b6b4
$primaryDim = e9a8a7
$onPrimary = 613333
$primaryContainer = 764544
$onPrimaryContainer = ffdbd9
$inversePrimary = 855150
$primaryFixed = febbba
$primaryFixedDim = efaeac
$onPrimaryFixed = 4e2424
$onPrimaryFixedVariant = 703f3f
$secondary = e6bdbb
$secondaryDim = d8afae
$onSecondary = 563938
$secondaryContainer = 503434
$onSecondaryContainer = dfb5b4
$secondaryFixed = ffdad8
$secondaryFixedDim = f5cac9
$onSecondaryFixed = 553837
$onSecondaryFixedVariant = 745353
$tertiary = ffcfef
$tertiaryDim = f3bfe3
$onTertiary = 69415f
$tertiaryContainer = f3bfe3
$onTertiaryContainer = 5f3956
$tertiaryFixed = f3bfe3
$tertiaryFixedDim = e5b2d5
$onTertiaryFixed = 4a2642
$onTertiaryFixedVariant = 694260
$error = f97758
$errorDim = c44f34
$onError = 450900
$errorContainer = 85230a
$onErrorContainer = ff9b82
$primaryPaletteKeyColor = a06867
$secondaryPaletteKeyColor = 916e6d
$tertiaryPaletteKeyColor = 956989
$neutralPaletteKeyColor = 807473
$neutralVariantPaletteKeyColor = 867372
$errorPaletteKeyColor = c75236
$primary_paletteKeyColor = a06867
$secondary_paletteKeyColor = 916e6d
$tertiary_paletteKeyColor = 956989
$neutral_paletteKeyColor = 807473
$neutral_variant_paletteKeyColor = 867372
$term0 = 080808
$term1 = ff5358
$term2 = ffbca6
$term3 = ffdfd8
$term4 = b3a2d5
$term5 = f08f96
$term6 = ffba93
$term7 = f0d2cb
$term8 = b49e99
$term9 = ff8481
$term10 = ffd4c6
$term11 = fff1ee
$term12 = dcbc93
$term13 = ffa7ab
$term14 = ffd1be
$term15 = ffffff
$rosewater = ffeeec
$flamingo = ffd9d8
$pink = ffd2d6
$mauve = ffa8bb
$red = ff969b
$maroon = f9aaab
$peach = ffbeb5
$yellow = ffede9
$green = ffd8c5
$teal = ffdb94
$sky = ebd1ff
$sapphire = f2b2f2
$blue = ffa0c6
$lavender = ffb9cf
$klink = bf6ba0
$klinkSelection = bf6ba0
$kvisited = cd5b75
$kvisitedSelection = cc5b76
$knegative = ec5259
$knegativeSelection = ec515b
$kneutral = ff887b
$kneutralSelection = ff887c
$kpositive = fd8c2a
$kpositiveSelection = fd8c2a
$text = f8e0df
$subtext1 = bca6a5
$subtext0 = 847170
$overlay2 = 1a1818
$overlay1 = 181515
$overlay0 = 151212
$surface2 = 120e0e
$surface1 = 0e0909
$surface0 = 070303
$base = 010000
$mantle = 010000
$crust = 010000
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
