$primary_paletteKeyColor = 8c6aa3
$secondary_paletteKeyColor = 807287
$tertiary_paletteKeyColor = 9d6a6d
$neutral_paletteKeyColor = 7b757c
$neutral_variant_paletteKeyColor = 7d757e
$background = 060406
$onBackground = e9e0e8
$surface = 060406
$surfaceDim = 060406
$surfaceBright = 111012
$surfaceContainerLowest = 040305
$surfaceContainerLow = 09070a
$surfaceContainer = 0a080b
$surfaceContainerHigh = 0e0c0e
$surfaceContainerHighest = 100f11
$onSurface = e9e0e8
$surfaceVariant = 151315
$onSurfaceVariant = cdc3ce
$inverseSurface = e9e0e8
$inverseOnSurface = 332f35
$outline = 968e98
$outlineVariant = 4b454d
$shadow = 000000
$scrim = 000000
$surfaceTint = 32213e
$primary = dfb8f7
$onPrimary = 412356
$primaryContainer = 593a6f
$onPrimaryContainer = f3daff
$inversePrimary = 725188
$secondary = d2c1d9
$onSecondary = 372c3f
$secondaryContainer = 4f4256
$onSecondaryContainer = efdcf5
$tertiary = f4b7ba
$onTertiary = 4c2528
$tertiaryContainer = b98385
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = f3daff
$primaryFixedDim = dfb8f7
$onPrimaryFixed = 2a0c40
$onPrimaryFixedVariant = 593a6f
$secondaryFixed = efdcf5
$secondaryFixedDim = d2c1d9
$onSecondaryFixed = 221729
$onSecondaryFixedVariant = 4f4256
$tertiaryFixed = ffdadb
$tertiaryFixedDim = f4b7ba
$onTertiaryFixed = 331014
$onTertiaryFixedVariant = 663b3e
$term0 = 080808
$term1 = e24ef6
$term2 = ffbac2
$term3 = ffdcf2
$term4 = aba4d7
$term5 = cd97db
$term6 = 9dceff
$term7 = e8d3de
$term8 = ae9ea7
$term9 = f377ff
$term10 = ffd2d5
$term11 = fff0f6
$term12 = babfdd
$term13 = dfaee7
$term14 = bae0ff
$term15 = ffffff
$rosewater = fbeef6
$flamingo = f1dbee
$pink = f4d1ff
$mauve = dcaefe
$red = de9deb
$maroon = dcb0e1
$peach = f3bdea
$yellow = ffecf3
$green = c8e3ff
$teal = dedcff
$sky = ded6ff
$sapphire = cebeff
$blue = ccafff
$lavender = ddc1ff
$klink = 9279cc
$klinkSelection = 9279cc
$kvisited = a367c9
$kvisitedSelection = a367c9
$knegative = c858dc
$knegativeSelection = c858dc
$kneutral = f67cf0
$kneutralSelection = f67df1
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e9e0e8
$subtext1 = cdc3ce
$subtext0 = 968e98
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 161516
$surface2 = 131213
$surface1 = 0f0d0f
$surface0 = 080608
$base = 010001
$mantle = 010001
$crust = 010001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
