# === AMBXST CONFIG ===

# 1. Limpieza
exec = pkill quickshell
exec = killall quickshell
exec = sleep 0.3

# 2. El Enlace Simbólico (La magia)
# Esto apunta el sistema (/etc/xdg/quickshell) hacia tu carpeta de ambxst
# Nota: Si tu usuario no tiene permisos en /etc, necesitarás usar 'sudo' o cambiar permisos antes.
# Si te da error de permisos, avísame para darte la alternativa sin sudo.
exec = sudo ln -sfn /home/jcgomez91/.config/quickshell/ambxst /etc/xdg/quickshell

# 3. Lanzar
exec = quickshell &
bind=Super+Alt, P, exec, qswitch --panel
exec = ~/.local/bin/smart_overview
