bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, nvim ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds
# Apagar el cerebro de DMS para ahorrar recursos
exec = systemctl --user stop dms.service
# Debe tener esto al principio:
exec = pkill dms
exec = ~/.local/bin/smart_overview
bind=Super+Alt, P, exec, qswitch --panel

