# --- Configuración SEGURA para DMS ---

# En lugar de ejecutar dms directamente, llamamos al guardia
exec = ~/.local/bin/smart_overview
exec = ~/.local/bin/start_dms_safe.sh
bind=Super+Alt, P, exec, qswitch --panel

