# exec = export SLURP_ARGS='-d -c FFDAD4BB -b 673B3444 -s 00000000'

general {
    col.active_border = rgb(6F4E37) rgb(9B6F4A) rgb(C7A17A) rgb(DAC2A5) rgb(ADC4D9) rgb(fab387) rgb(f5c2e7) rgb(c8b6a6) rgb(a77464) rgb(c8b6a6) 60deg        
    col.inactive_border = rgba(F7DCDE39)
}

misc {
    background_color = rgba(1D1011FF)
}
 ######################## PLUGIN JC ########################
plugin {
    hyprbars {
        # Honestly idk if it works like css, but well, why not
        bar_text_font = Google Sans Flex Medium, Rubik, Geist, AR One Sans, Reddit Sans, Inter, Roboto, Ubuntu, Noto Sans, sans-serif
        bar_height = 30
        bar_padding = 10
        bar_button_padding = 5
        bar_precedence_over_border = true
        bar_part_of_window = true

        bar_color = rgba(1D1011FF)
        col.text = rgba(F7DCDEFF)


        # example buttons (R -> L)
        # hyprbars-button = color, size, on-click
       hyprbars-button = rgb(F7DCDE), 18, 󰖭, hyprctl dispatch killactive
        hyprbars-button = rgb(F7DCDE), 18, 󰖯, hyprctl dispatch fullscreen 1
        hyprbars-button = rgb(F7DCDE), 18, 󰖰, hyprctl dispatch movetoworkspacesilent special 
        hyprbars-button = rgb(F7DCDE), 18, ,kitty
        hyprbars-button = rgb(F7DCDE), 18, , gedit 
        hyprbars-button = rgb(F7DCDE), 18, , firefox
    }
}

plugin {
    hyprfocus {
    mode = flash 
   #mode = bounce 
   #mode = slide 
   
    fade_opacity = 0.8
   #bounce_strength = 0.95
   #slide_height = 20
    
         }
         
}

# --- CONFIGURACIÓN DEL PLUGIN HYPRSCROLLING ---

plugin {
    hyprscrolling {
        column_width = 0.7              # Tu valor preferido
        fullscreen_on_one_column = false # Tu valor preferido
        focus_fit_method = 1            # 1 = "fit" (ajustar)
    }
}

# --- ATAJOS PARA MOVERSE EN MODO SCROLLING ---
# Estos son esenciales para usar este modo.
# Puedes cambiar "comma" (,) y "period" (.) por las teclas que gustes.

# Desplazarse izquierda/derecha por las columnas
bind = SUPER, period, layoutmsg, move +col
bind = SUPER, comma, layoutmsg, move -col

# Mover la ventana activa a otra columna
bind = SUPER SHIFT, period, layoutmsg, movewindowto r
bind = SUPER SHIFT, comma, layoutmsg, movewindowto l

# Centrar la columna actual
bind = SUPER, c, layoutmsg, focus active

# Navegar entre ventanas (scrolling) con SUPER + CTRL + RUEDA
bind = CTRL Alt, mouse_down, layoutmsg, move +col
bind = CTRL Alt, mouse_up, layoutmsg, move -col
# Atajo para activar/desactivar Hyprscrolling
bind = Alt, Tab, exec, ~/.config/hypr/scripts/toggle_scrolling.sh

windowrule = border_color rgba(FFB2BCAA) rgba(FFB2BC77), match:pin 1
