decoration:blur:popups = 0
decoration:dim_special = 0.95
decoration:blur:contrast = 1.79
general:layout = master
general:col.active_border = rgba(8fd3ffff) rgba(4facfeff) rgba(00c6ffff) 90deg
general:col.inactive_border = rgba(2b2f3acc) rgba(454b5acc) 90deg
decoration:blur:new_optimizations = 0
decoration:blur:ignore_opacity = 0
decoration:blur:size = 30
decoration:blur:passes = 8
decoration:blur:vibrancy = 0.72
decoration:blur:brightness = 1.40
decoration:blur:noise = 0.090
decoration:inactive_opacity = 1.00
decoration:dim_inactive = 1
decoration:dim_around = 0.30
decoration:dim_strength = 0.18
decoration:shadow:range = 35
decoration:shadow:render_power = 1
decoration:shadow:scale = 1.25
decoration:shadow:ignore_window = 0
decoration:shadow:color = rgba(00ff9970)
decoration:shadow:enabled = 0
decoration:rounding_power = 2.5
decoration:rounding = 20
input:touchpad:natural_scroll = 1
misc:middle_click_paste = 1
general:gaps_workspaces = 60
general:gaps_out = 2
general:gaps_in = 2
general:border_size = 1
general:extend_border_grab_area = 15
misc:mouse_move_enables_dpms = 1
animations:enabled = 1
general:resize_on_border = 1
decoration:blur:enabled = 1
decoration:blur:xray = 1
